name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: |
          npm --version
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm config list
          npm ping 2>&1
          npm whoami 2>&1
          npm publish --access public --registry=https://registry.npmjs.org 2>&1
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

